import { signIn, signOut, useSession } from "next-auth/react";
import Head from "next/head";
import Link from "next/link";
import { api } from "~/utils/api";
import { SignInButton, SignOutButton, useUser } from "@clerk/nextjs";
import { auth } from "@clerk/nextjs";

export default function Home() {
  const hello = api.example.hello.useQuery({ text: "from tRPC" });
  const user = useUser();

  console.log(user.user?.username);

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main></main>

      <div className="bg-slate-900">
        <div className="bg-gradient-to-b from-violet-600/[.15] via-transparent">
          <div className="mx-auto max-w-[85rem] space-y-8 px-4 py-24 sm:px-6 lg:px-8">
            <div className="flex justify-center">
              <a
                className="group inline-block rounded-full border border-white/[.05] bg-white/[.05] p-1 ps-4 shadow-md hover:bg-white/[.1]"
                href="../figma.html"
              >
                <p className="me-2 inline-block text-sm text-white">
                  Preline UI Figma is live.
                </p>
                <span className="inline-flex items-center justify-center gap-x-2 rounded-full bg-white/[.075] px-2.5 py-1.5 text-sm font-semibold text-white group-hover:bg-white/[.1]">
                  <svg
                    className="h-4 w-4 flex-shrink-0"
                    width="16"
                    height="16"
                    viewBox="0 0 16 16"
                    fill="none"
                  >
                    <path
                      d="M5.27921 2L10.9257 7.64645C11.1209 7.84171 11.1209 8.15829 10.9257 8.35355L5.27921 14"
                      stroke="currentColor"
                      stroke-width="2"
                      stroke-linecap="round"
                    />
                  </svg>
                </span>
              </a>
            </div>

            <div className="mx-auto max-w-3xl text-center">
              <h1 className="block text-4xl font-medium text-gray-200 sm:text-5xl md:text-6xl lg:text-7xl">
                Now it's easier than ever to build products
              </h1>
            </div>

            <div className="mx-auto max-w-3xl text-center">
              <p className="text-lg text-gray-400">
                Preline is a large open-source project, crafted with Tailwind
                CSS framework by Hmlstream.
              </p>
            </div>

            <div className="text-center">
              <a
                className="inline-flex items-center justify-center gap-x-3 rounded-full border border-transparent bg-gradient-to-tl from-blue-600 to-violet-600 px-6 py-3 text-center text-sm font-medium text-white shadow-lg shadow-transparent hover:shadow-blue-700/50 focus:outline-none focus:ring-2 focus:ring-blue-600 focus:ring-offset-2 focus:ring-offset-white dark:focus:ring-offset-gray-800"
                href="#"
              >
                Get started
                <svg
                  className="h-4 w-4 flex-shrink-0"
                  xmlns="http://www.w3.org/2000/svg"
                  width="24"
                  height="24"
                  viewBox="0 0 24 24"
                  fill="none"
                  stroke="currentColor"
                  stroke-width="2"
                  stroke-linecap="round"
                  stroke-linejoin="round"
                >
                  <path d="m9 18 6-6-6-6" />
                </svg>
              </a>
            </div>
          </div>
        </div>
        <p className="me-2 inline-block text-sm text-white">
          {user.user?.username}
        </p>
        <SignInButton />
        <SignOutButton />
      </div>
    </>
  );
}
